"""adiciona turno ao fechamento de caixa

Revision ID: 1f1b0347416d
Revises: e6cfc6ef6c3b
Create Date: 2026-08-19 15:41:10.069839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1b0347416d'
down_revision: Union[str, None] = 'e6cfc6ef6c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fechamentos_caixa', sa.Column('turno', sa.String(length=10), nullable=False))
    op.drop_constraint('fechamentos_caixa_data_key', 'fechamentos_caixa', type_='unique')
    op.create_unique_constraint('uq_fechamentos_caixa_data_turno', 'fechamentos_caixa', ['data', 'turno'])
    # ### end Alembic commands ###
    # Alembic autogenerate não detecta CheckConstraint — adicionado manualmente.
    op.create_check_constraint(
        'ck_fechamentos_caixa_turno_valido',
        'fechamentos_caixa',
        "turno IN ('Manhã', 'Noite')",
    )


def downgrade() -> None:
    op.drop_constraint('ck_fechamentos_caixa_turno_valido', 'fechamentos_caixa', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fechamentos_caixa_data_turno', 'fechamentos_caixa', type_='unique')
    op.create_unique_constraint('fechamentos_caixa_data_key', 'fechamentos_caixa', ['data'], postgresql_nulls_not_distinct=False)
    op.drop_column('fechamentos_caixa', 'turno')
    # ### end Alembic commands ###
